# Generated by Django 3.1.3 on 2021-01-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('register', '0002_auto_20210116_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30, verbose_name='Course or Flight')),
                ('points1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gross Points')),
                ('points2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Net Points')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='events.event', verbose_name='Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.player', verbose_name='Player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playerpoints',
            constraint=models.UniqueConstraint(fields=('event', 'player'), name='unique_event_player'),
        ),
    ]
