# Generated by Django 3.1.2 on 2020-10-19 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(max_length=40, verbose_name='Payment code')),
                ('payment_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Payment code')),
                ('notification_type', models.CharField(blank=True, choices=[('N', 'New Member'), ('R', 'Returning Member'), ('C', 'Signup Confirmation')], max_length=1, null=True, verbose_name='Notification type')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='events.event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
