# Generated by Django 3.1.3 on 2020-11-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment code'),
        ),
    ]
