# Generated by Django 3.1.3 on 2020-11-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20201127_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Payment amount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Payment fees'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Secret key'),
        ),
    ]
