# Generated by Django 3.1.3 on 2021-03-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('A', 'Admin'), ('N', 'New Member'), ('R', 'Returning Member'), ('C', 'Signup Confirmation'), ('M', 'Match Play'), ('O', 'General Online Payment')], max_length=1, null=True, verbose_name='Notification type'),
        ),
    ]
