# Generated by Django 3.1.3 on 2020-12-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20201127_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('N', 'New Member'), ('R', 'Returning Member'), ('C', 'Signup Confirmation'), ('M', 'Match Play'), ('O', 'General Online Payment')], max_length=1, null=True, verbose_name='Notification type'),
        ),
    ]
