# Generated by Django 3.1.3 on 2021-03-14 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_auto_20210307_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_code', models.CharField(max_length=40, verbose_name='Payment code')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Payment amount')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('refund_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Refund date')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='Payment')),
            ],
        ),
    ]
