# Generated by Django 4.1.4 on 2022-12-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20210319_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirm_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirm date'),
        ),
    ]
