# Generated by Django 5.2.9 on 2025-12-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_confirm_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('A', 'Admin'), ('N', 'New Member'), ('R', 'Returning Member'), ('C', 'Signup Confirmation'), ('M', 'Match Play'), ('U', 'Update Registration')], max_length=1, null=True, verbose_name='Notification type'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_code',
            field=models.CharField(max_length=40, unique=True, verbose_name='Refund code'),
        ),
    ]
