# Generated by Django 4.2.7 on 2024-01-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventscore',
            options={'verbose_name': 'Event Scores', 'verbose_name_plural': 'Event Scores'},
        ),
    ]
