# Generated by Django 5.1.3 on 2025-10-06 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_tee'),
        ('scores', '0002_alter_eventscore_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscore',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='eventscore',
            name='tee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.tee', verbose_name='Tee'),
        ),
    ]
