# Generated by Django 5.1.3 on 2025-10-26 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_tee'),
        ('events', '0018_alter_tournamentresult_team_id'),
        ('register', '0014_historicalplayer_gg_id_player_gg_id_and_more'),
        ('scores', '0003_eventscore_course_eventscore_tee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventscore',
            options={'verbose_name': 'Event Score', 'verbose_name_plural': 'Event Scores'},
        ),
        migrations.AlterField(
            model_name='eventscore',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='eventscore',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.player', verbose_name='Player'),
        ),
        migrations.CreateModel(
            name='EventScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap_index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Handicap Index')),
                ('course_handicap', models.IntegerField(default=0, verbose_name='Course Handicap')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course', verbose_name='Course')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.player', verbose_name='Player')),
                ('tee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.tee', verbose_name='Tee')),
            ],
            options={
                'verbose_name': 'Event Scorecard',
                'verbose_name_plural': 'Event Scorecards',
            },
        ),
        migrations.AddField(
            model_name='eventscore',
            name='scorecard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scores.eventscorecard', verbose_name='Scorecard'),
        ),
        migrations.AddConstraint(
            model_name='eventscorecard',
            constraint=models.UniqueConstraint(fields=('event', 'player'), name='unique_event_scorecard'),
        ),
    ]
