# Generated by Django 5.2.9 on 2026-01-14 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_alter_eventscore_options_alter_eventscore_event_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventscore',
            name='unique_event_score',
        ),
        migrations.RemoveField(
            model_name='eventscore',
            name='course',
        ),
        migrations.RemoveField(
            model_name='eventscore',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventscore',
            name='player',
        ),
        migrations.RemoveField(
            model_name='eventscore',
            name='tee',
        ),
        migrations.AlterField(
            model_name='eventscore',
            name='scorecard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scores.eventscorecard', verbose_name='Scorecard'),
        ),
    ]
