# Generated by Django 3.1.2 on 2020-10-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Fee Name'),
        ),
    ]
