# Generated by Django 3.1.2 on 2020-10-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201018_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfee',
            name='fee_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='events.feetype', verbose_name='Fee Type'),
            preserve_default=False,
        ),
    ]
