# Generated by Django 3.1.2 on 2020-10-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventfee_fee_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('name', 'start_date'), name='unique_name_startdate'),
        ),
        migrations.AddConstraint(
            model_name='eventfee',
            constraint=models.UniqueConstraint(fields=('event', 'fee_type'), name='unique_event_feetype'),
        ),
    ]
