# Generated by Django 4.0.2 on 2022-02-06 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_auto_20211121_1127"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventfee",
            options={"ordering": ["display_order"]},
        ),
    ]
