# Generated by Django 3.1.3 on 2020-11-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201021_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='code',
            field=models.CharField(default='X', max_length=3, verbose_name='Fee Code'),
        ),
    ]
