# Generated by Django 3.1.3 on 2020-12-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_feetype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.IntegerField(default=0, verbose_name='Season'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='season',
            field=models.IntegerField(default=0, verbose_name='Season'),
        ),
    ]
