# Generated by Django 5.1.3 on 2025-09-19 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_gg_id"),
        ("events", "0013_event_age_restriction_event_age_restriction_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="gg_id",
            field=models.CharField(
                blank=True,
                max_length=22,
                null=True,
                verbose_name="Golf Genius id: event_id",
            ),
        ),
        migrations.AddField(
            model_name="historicalevent",
            name="gg_id",
            field=models.CharField(
                blank=True,
                max_length=22,
                null=True,
                verbose_name="Golf Genius id: event_id",
            ),
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField(verbose_name="Round number")),
                ("round_date", models.DateField(verbose_name="Round date")),
                (
                    "gg_id",
                    models.CharField(
                        max_length=22, verbose_name="Golf Genius id: round_id"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gg_rounds",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Tournament name"),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Format"
                    ),
                ),
                ("is_net", models.BooleanField(default=False, verbose_name="Is Net")),
                (
                    "gg_id",
                    models.CharField(
                        max_length=22, verbose_name="Golf Genius id: tournament_id"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gg_tournaments",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gg_rounds",
                        to="events.round",
                        verbose_name="Round",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("event", "round_number"), name="unique_event_roundnumber"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="unique_event_tournamentname"
            ),
        ),
    ]
