# Generated by Django 5.1.3 on 2025-10-09 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_event_gg_id_historicalevent_gg_id_round_tournament_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="course",
        ),
    ]
