# Generated by Django 5.1.3 on 2025-10-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_tournamentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentresult',
            name='team_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Team id'),
        ),
    ]
