# Generated by Django 5.1.3 on 2025-10-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_tournamentresult_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentresult',
            name='team_id',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='Team id'),
        ),
    ]
