# Generated by Django 5.1.3 on 2025-11-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_tournamentresult_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentresult',
            name='points',
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='payout_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and Time Paid'),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='payout_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Paid', 'Paid')], max_length=10, null=True, verbose_name='Payout Status'),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='payout_to',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Team', 'Team')], max_length=10, null=True, verbose_name='Payout To'),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='payout_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=10, null=True, verbose_name='Payout Type'),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='summary',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Summary'),
        ),
    ]
