# Generated by Django 5.1.3 on 2025-11-08 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_tournamentresult_points_and_more'),
        ('register', '0014_historicalplayer_gg_id_player_gg_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=999, verbose_name='Position')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('details', models.CharField(blank=True, max_length=120, null=True, verbose_name='Details')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_long_points', to='register.player', verbose_name='Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_long_points', to='events.tournament', verbose_name='Tournament')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tournament', 'player'), name='unique_points')],
            },
        ),
    ]
