# Generated by Django 5.1.3 on 2025-11-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_tournamentpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='payout',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Passthru', 'Passthru'), ('None', 'None')], default='Credit', max_length=12, verbose_name='Payout Type'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='payout_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Passthru', 'Passthru'), ('None', 'None')], max_length=10, null=True, verbose_name='Payout Type'),
        ),
    ]
