# Generated by Django 5.2.9 on 2025-12-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_feetype_payout_alter_tournamentresult_payout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signup_waves',
            field=models.IntegerField(blank=True, null=True, verbose_name='Signup waves'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='signup_waves',
            field=models.IntegerField(blank=True, null=True, verbose_name='Signup waves'),
        ),
    ]
