# Generated by Django 5.2.9 on 2025-12-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_event_signup_waves_historicalevent_signup_waves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('Skins', 'Skins'), ('Stroke', 'Stroke'), ('Team', 'Team'), ('Quota', 'Quota'), ('UserScored', 'UserScored'), ('Other', 'Other')], max_length=20, verbose_name='Format'),
        ),
    ]
