# Generated by Django 5.2.9 on 2025-12-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_tournament_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentresult',
            name='summary',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Summary'),
        ),
    ]
