# Generated by Django 3.1.3 on 2021-01-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '__first__'),
        ('register', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Current golf season')),
                ('accept_new_members', models.BooleanField(default=False, verbose_name='Accepting new member registration?')),
                ('match_play_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_play', to='events.event', verbose_name='Match play event')),
                ('reg_event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='season_registration', to='events.event', verbose_name='Registration event')),
            ],
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=40, verbose_name='Role')),
                ('term_expires', models.IntegerField(verbose_name='Member thru')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.player', verbose_name='Player')),
            ],
        ),
    ]
