# Generated by Django 3.1.3 on 2021-01-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=40, verbose_name='Role')),
                ('term_expires', models.IntegerField(verbose_name='Member thru')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.player', verbose_name='Player')),
            ],
        ),
    ]
