# Generated by Django 3.1.3 on 2021-01-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorChampion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(verbose_name='Season')),
                ('event_name', models.CharField(max_length=60, verbose_name='Event name')),
                ('flight', models.CharField(max_length=30, verbose_name='Flight')),
                ('score', models.CharField(max_length=20, verbose_name='Score')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.player', verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='LowScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(verbose_name='Season')),
                ('course_name', models.CharField(max_length=40, verbose_name='Event name')),
                ('score', models.CharField(max_length=20, verbose_name='Score')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.player', verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='Ace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(verbose_name='Season')),
                ('hole_name', models.CharField(max_length=30, verbose_name='Event name')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.player', verbose_name='Player')),
            ],
        ),
    ]
