# Generated by Django 3.1.3 on 2021-04-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210116_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ace',
            name='shot_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
    ]
