# Generated by Django 3.1.3 on 2021-04-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ace_shot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ace',
            name='shot_date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
