# Generated by Django 3.1.3 on 2021-12-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20211121_1127'),
        ('core', '0005_auto_20210408_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(verbose_name='Season')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('match_play_event_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_play_event', to='events.event', verbose_name='Match Play Event')),
                ('member_event_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_event', to='events.event', verbose_name='Membership Event')),
            ],
        ),
    ]
