# Generated by Django 4.2.7 on 2023-11-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_match_play_event_id_seasonsettings_match_play_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowscore',
            name='is_net',
            field=models.BooleanField(default=False, verbose_name='Is net score'),
        ),
    ]
