# Generated by Django 4.2.7 on 2023-11-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lowscore_is_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowscore',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
