# Generated by Django 4.2.7 on 2023-11-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_lowscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorchampion',
            name='is_net',
            field=models.BooleanField(default=False, verbose_name='Is net score'),
        ),
        migrations.AlterField(
            model_name='majorchampion',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
