# Generated by Django 5.1.3 on 2025-11-02 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_majorchampion_team_id'),
        ('events', '0018_alter_tournamentresult_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfGeniusIntegrationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=20, verbose_name='Action Name')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('is_successful', models.BooleanField(verbose_name='Action Completed Successfully')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Serialized Details')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='integration_logs', to='events.event', verbose_name='Event')),
            ],
        ),
    ]
