# Generated by Django 4.1.4 on 2022-12-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpolicy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical policy', 'verbose_name_plural': 'historical Policies'},
        ),
        migrations.AlterField(
            model_name='historicalpolicy',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
