# Generated by Django 5.1.3 on 2025-09-10 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('events', '0013_event_age_restriction_event_age_restriction_type_and_more'),
        ('register', '0013_remove_historicalregistration_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(choices=[('Gross', 'Gross'), ('Net', 'Net')], max_length=5, verbose_name='Skin Type')),
                ('skin_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Skin Amount')),
                ('is_team', models.BooleanField(default=False, verbose_name='Is Team')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course', verbose_name='Course')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.event', verbose_name='Event')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.hole', verbose_name='Hole')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.player', verbose_name='Player')),
            ],
            options={
                'ordering': ['-event__start_date', 'hole__hole_number'],
            },
        ),
        migrations.CreateModel(
            name='SkinSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_frequency', models.CharField(choices=[('Bi-Monthly', 'Bi-Monthly'), ('Monthly', 'Monthly'), ('Season End', 'Season End')], max_length=10, verbose_name='Payment Frequency')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.player', verbose_name='Player')),
            ],
            options={
                'verbose_name_plural': 'Skin Settings',
            },
        ),
        migrations.CreateModel(
            name='SkinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(verbose_name='Season')),
                ('transaction_type', models.CharField(max_length=20, verbose_name='Transaction Type')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Transaction Amount')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('transaction_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Timestamp')),
                ('direction', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], max_length=8, verbose_name='Direction')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.player', verbose_name='Player')),
            ],
            options={
                'ordering': ['-transaction_date', '-transaction_timestamp'],
            },
        ),
    ]
