# Generated by Django 5.1.3 on 2025-09-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='details',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Details'),
        ),
    ]
