# Generated by Django 3.1.3 on 2021-01-02 13:47

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('R', 'Event Results'), ('T', 'Event Tee Times'), ('P', 'Season Long Points'), ('D', 'Dam Cup'), ('M', 'Match Play'), ('F', 'Financial Statements'), ('S', 'Sign Up'), ('O', 'Other')], default='R', max_length=1, verbose_name='Type')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Golf Season')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('file', models.FileField(upload_to=documents.models.document_directory_path, verbose_name='File')),
                ('created_by', models.CharField(max_length=100, verbose_name='Created By')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='events.event', verbose_name='Event')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='Golf Season')),
                ('player_id', models.IntegerField(blank=True, null=True, verbose_name='Player Id')),
                ('caption', models.CharField(blank=True, max_length=240, null=True, verbose_name='Caption')),
                ('raw_image', models.ImageField(upload_to=documents.models.photo_directory_path, verbose_name='Image')),
                ('created_by', models.CharField(max_length=100, verbose_name='Created By')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='documents.photo', verbose_name='Photo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.tag', verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='documents.document', verbose_name='Document')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.tag', verbose_name='Tag')),
            ],
        ),
    ]
