# Generated by Django 3.1.3 on 2021-04-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('R', 'Event Results'), ('T', 'Event Tee Times'), ('P', 'Season Long Points'), ('D', 'Dam Cup'), ('M', 'Match Play'), ('F', 'Financial Statements'), ('S', 'Sign Up'), ('O', 'Other'), ('Z', 'Data')], default='R', max_length=1, verbose_name='Type'),
        ),
    ]
