# Generated by Django 3.1.3 on 2020-11-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphoto',
            name='player_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Player Id'),
        ),
        migrations.AddField(
            model_name='photo',
            name='player_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Player Id'),
        ),
        migrations.AlterField(
            model_name='historicalphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Caption'),
        ),
    ]
