# Generated by Django 3.1.3 on 2020-12-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20201121_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalphoto',
            name='history_user',
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('R', 'Event Results'), ('T', 'Event Tee Times'), ('P', 'Season Long Points'), ('D', 'Dam Cup'), ('M', 'Match Play'), ('F', 'Financial Statements'), ('S', 'Sign Up'), ('O', 'Other')], default='R', max_length=1, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='HistoricalDocument',
        ),
        migrations.DeleteModel(
            name='HistoricalPhoto',
        ),
    ]
