# Generated by Django 3.1.3 on 2021-11-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_tag'),
        ('documents', '0003_staticdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='phototag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tag', verbose_name='Tag'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
