# Generated by Django 4.2.7 on 2023-12-23 18:46

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20211121_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('R', 'Event Results'), ('T', 'Event Tee Times'), ('L', 'Event Flights'), ('P', 'Season Long Points'), ('D', 'Dam Cup'), ('M', 'Match Play'), ('F', 'Financial Statements'), ('S', 'Sign Up'), ('O', 'Other'), ('Z', 'Data')], default='R', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to=documents.models.document_directory_path, verbose_name='File'),
        ),
    ]
