# Generated by Django 4.2.7 on 2024-01-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_document_type_alter_document_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticdocument',
            options={'verbose_name': 'Club Document', 'verbose_name_plural': 'Club Documents'},
        ),
    ]
