# Generated by Django 3.1.2 on 2020-10-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregistration',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='confirmation_code',
        ),
        migrations.AddConstraint(
            model_name='registrationslot',
            constraint=models.UniqueConstraint(fields=('event', 'player'), name='unique_player_registration'),
        ),
    ]
