# Generated by Django 3.1.3 on 2020-11-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201021_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplayer',
            name='save_last_card',
            field=models.BooleanField(default=False, verbose_name='Save Last Card Used'),
        ),
        migrations.AddField(
            model_name='historicalplayer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Stripe ID'),
        ),
        migrations.AddField(
            model_name='player',
            name='save_last_card',
            field=models.BooleanField(default=False, verbose_name='Save Last Card Used'),
        ),
        migrations.AddField(
            model_name='player',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Stripe ID'),
        ),
    ]
