# Generated by Django 3.1.3 on 2021-03-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210116_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationslot',
            options={'ordering': ('hole', 'slot')},
        ),
    ]
