# Generated by Django 3.1.3 on 2020-11-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20201121_1111'),
        ('register', '0003_auto_20201118_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplayer',
            name='profile_picture',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.photo', verbose_name='Profile picture'),
        ),
        migrations.AddField(
            model_name='player',
            name='profile_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.photo', verbose_name='Profile picture'),
        ),
    ]
