# Generated by Django 3.1.3 on 2020-11-29 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0004_auto_20201121_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistration',
            name='signed_up_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Signed up by'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='signed_up_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Signed up by'),
        ),
    ]
