# Generated by Django 3.1.3 on 2020-11-29 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20201128_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalregistration',
            old_name='signed_up_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='signed_up_by',
            new_name='user',
        ),
    ]
