# Generated by Django 3.1.3 on 2020-11-29 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20201128_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalRegistration',
        ),
    ]
