# Generated by Django 3.1.3 on 2021-10-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20211024_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerhandicap',
            options={'ordering': ('season', 'handicap')},
        ),
        migrations.RemoveField(
            model_name='historicalplayerhandicap',
            name='index',
        ),
        migrations.RemoveField(
            model_name='playerhandicap',
            name='index',
        ),
        migrations.AddField(
            model_name='historicalplayerhandicap',
            name='handicap',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Year End Index'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerhandicap',
            name='handicap',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Year End Index'),
            preserve_default=False,
        ),
    ]
