# Generated by Django 3.1.3 on 2021-11-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20211024_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistrationslot',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('P', 'Pending'), ('X', 'Payment Processing'), ('R', 'Reserved'), ('U', 'Unavailable')], default='A', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='registrationslot',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('P', 'Pending'), ('X', 'Payment Processing'), ('R', 'Reserved'), ('U', 'Unavailable')], default='A', max_length=1, verbose_name='Status'),
        ),
    ]
