# Generated by Django 3.1.3 on 2020-11-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_historicalregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.AddField(
            model_name='historicalregistration',
            name='signed_up_by',
            field=models.CharField(blank=True, max_length=40, verbose_name='Signed up by'),
        ),
        migrations.AddField(
            model_name='registration',
            name='signed_up_by',
            field=models.CharField(blank=True, max_length=40, verbose_name='Signed up by'),
        ),
    ]
