# Generated by Django 4.0.2 on 2022-02-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20211121_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='register.Player'),
        ),
    ]
