# Generated by Django 4.1.4 on 2022-12-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_player_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalplayer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical player', 'verbose_name_plural': 'historical players'},
        ),
        migrations.AlterModelOptions(
            name='historicalplayerhandicap',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical player handicap', 'verbose_name_plural': 'historical player handicaps'},
        ),
        migrations.AlterModelOptions(
            name='historicalregistration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical registration', 'verbose_name_plural': 'historical registrations'},
        ),
        migrations.AlterModelOptions(
            name='historicalregistrationslot',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical registration slot', 'verbose_name_plural': 'historical registration slots'},
        ),
        migrations.AlterField(
            model_name='historicalplayer',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalplayerhandicap',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalregistration',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalregistrationslot',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
