# Generated by Django 3.1.3 on 2020-12-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20201129_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplayer',
            name='save_last_card',
            field=models.BooleanField(default=True, verbose_name='Save Last Card Used'),
        ),
        migrations.AlterField(
            model_name='player',
            name='save_last_card',
            field=models.BooleanField(default=True, verbose_name='Save Last Card Used'),
        ),
    ]
