# Generated by Django 3.1.3 on 2020-12-25 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20201219_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistration',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 14, 58, 24, 590321), verbose_name='Created date'),
        ),
        migrations.AddField(
            model_name='registration',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 14, 58, 24, 590321), verbose_name='Created date'),
        ),
    ]
