# Generated by Django 4.2.7 on 2023-12-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_historicalplayer_is_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Amount Paid'),
        ),
    ]
