# Generated by Django 3.1.3 on 2020-12-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20201225_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistration',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
    ]
