# Generated by Django 5.1.3 on 2025-01-14 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_registrationfee_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregistration',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalregistration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='historicalregistration',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalregistrationslot',
            name='event',
        ),
        migrations.RemoveField(
            model_name='historicalregistrationslot',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalregistrationslot',
            name='hole',
        ),
        migrations.RemoveField(
            model_name='historicalregistrationslot',
            name='player',
        ),
        migrations.RemoveField(
            model_name='historicalregistrationslot',
            name='registration',
        ),
        migrations.DeleteModel(
            name='HistoricalPlayerHandicap',
        ),
        migrations.DeleteModel(
            name='HistoricalRegistration',
        ),
        migrations.DeleteModel(
            name='HistoricalRegistrationSlot',
        ),
    ]
