# Generated by Django 5.1.3 on 2025-09-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_remove_historicalregistration_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplayer',
            name='gg_id',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='Golf Genius id: member_card_id'),
        ),
        migrations.AddField(
            model_name='player',
            name='gg_id',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='Golf Genius id: member_card_id'),
        ),
        migrations.AddField(
            model_name='registration',
            name='gg_id',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='Golf Genius id: group_id from the teesheet'),
        ),
        migrations.AddField(
            model_name='registrationslot',
            name='gg_id',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='Golf Genius id: member_id specific to this event'),
        ),
    ]
