# Generated by Django 5.1.3 on 2025-11-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_historicalplayer_user_id_player_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalplayer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='user_id',
            new_name='user',
        ),
    ]
