# Generated by Django 5.2.9 on 2025-12-22 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_rename_user_id_historicalplayer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='starting_hole',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='starting_order',
        ),
    ]
