# Generated by Django 5.1.3 on 2025-09-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='gg_id',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='Golf Genius id: course_id'),
        ),
    ]
