# Generated by Django 3.1.2 on 2020-10-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hole',
            constraint=models.UniqueConstraint(fields=('course', 'hole_number'), name='unique_course_holenumber'),
        ),
    ]
