# Generated by Django 5.1.3 on 2025-10-06 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_gg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gg_id', models.CharField(blank=True, max_length=22, null=True, verbose_name='Golf Genius id: tee_id')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tees', to='courses.course')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'name'), name='unique_course_tee')],
            },
        ),
    ]
