# Generated by Django 3.1.2 on 2020-10-19 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.CharField(max_length=254, verbose_name='Email')),
                ('message_text', models.TextField(verbose_name='Message text')),
                ('message_date', models.DateTimeField(auto_now_add=True, verbose_name='Message date')),
            ],
        ),
        migrations.CreateModel(
            name='WebContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('H', 'Home'), ('DC', 'Dam Cup'), ('MP', 'Match Play'), ('CC', 'Code of Conduct')], max_length=2, verbose_name='Type')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWebContent',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('H', 'Home'), ('DC', 'Dam Cup'), ('MP', 'Match Play'), ('CC', 'Code of Conduct')], max_length=2, verbose_name='Type')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('content', models.TextField(verbose_name='Content')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical web content',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAnnouncement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('text', models.TextField(verbose_name='Announcement text')),
                ('starts', models.DateTimeField(verbose_name='Display start')),
                ('expires', models.DateTimeField(verbose_name='Display expiration')),
                ('visibility', models.CharField(choices=[('M', 'Members Only'), ('N', 'Non-members Only'), ('A', 'All')], default='A', max_length=1, verbose_name='Who should see the message?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.event', verbose_name='Event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical announcement',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('text', models.TextField(verbose_name='Announcement text')),
                ('starts', models.DateTimeField(verbose_name='Display start')),
                ('expires', models.DateTimeField(verbose_name='Display expiration')),
                ('visibility', models.CharField(choices=[('M', 'Members Only'), ('N', 'Non-members Only'), ('A', 'All')], default='A', max_length=1, verbose_name='Who should see the message?')),
                ('documents', models.ManyToManyField(blank=True, to='documents.Document', verbose_name='Document(s)')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.event', verbose_name='Event')),
            ],
        ),
    ]
