# Generated by Django 3.1.3 on 2020-12-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwebcontent',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='WebContent',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalannouncement',
            name='name',
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalannouncement',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistoricalWebContent',
        ),
    ]
