# Generated by Django 3.1.3 on 2021-01-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamCup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(verbose_name='Season')),
                ('good_guys', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Good Guys')),
                ('bad_guys', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Bad Guys')),
            ],
        ),
        migrations.AddConstraint(
            model_name='damcup',
            constraint=models.UniqueConstraint(fields=('season',), name='unique_season'),
        ),
    ]
