# Generated by Django 3.1.3 on 2021-01-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damcup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damcup',
            name='site',
            field=models.CharField(default='Bunker', max_length=30, verbose_name='Site'),
            preserve_default=False,
        ),
    ]
