# Generated by Django 3.1.3 on 2021-04-03 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210307_0914'),
        ('register', '0005_auto_20210319_1849'),
        ('damcup', '0002_damcup_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonLongPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Gross Points')),
                ('net_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Net Points')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.player', verbose_name='Player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='seasonlongpoints',
            constraint=models.UniqueConstraint(fields=('event', 'player'), name='unique_slp'),
        ),
    ]
