# Generated by Django 3.1.3 on 2021-04-03 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20210402_1904'),
        ('damcup', '0003_auto_20210402_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonlongpoints',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.document', verbose_name='Source'),
            preserve_default=False,
        ),
    ]
