# Generated by Django 3.1.3 on 2021-04-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damcup', '0005_auto_20210425_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonlongpoints',
            name='gross_points',
            field=models.IntegerField(default=0, verbose_name='Gross Points'),
        ),
        migrations.AlterField(
            model_name='seasonlongpoints',
            name='net_points',
            field=models.IntegerField(default=0, verbose_name='Net Points'),
        ),
    ]
