# Generated by Django 3.1.3 on 2021-05-29 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('events', '0003_auto_20210307_0914'),
        ('register', '0005_auto_20210319_1849'),
        ('damcup', '0006_auto_20210425_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.hole', verbose_name='Hole')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.player', verbose_name='Player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scores',
            constraint=models.UniqueConstraint(fields=('event', 'player', 'hole'), name='unique_score'),
        ),
    ]
