# Generated by Django 4.2.7 on 2024-01-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damcup', '0007_auto_20210528_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonlongpoints',
            options={'verbose_name': 'Season Long Points', 'verbose_name_plural': 'Season Long Points'},
        ),
    ]
