# Generated by Django 5.1.3 on 2025-11-04 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damcup', '0008_alter_seasonlongpoints_options'),
        ('events', '0019_remove_tournamentresult_points_and_more'),
        ('register', '0014_historicalplayer_gg_id_player_gg_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=999, verbose_name='Position')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('is_net', models.BooleanField(default=False, verbose_name='Is Net')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('division', models.CharField(blank=True, max_length=40, null=True, verbose_name='Course, Division, Flight')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_long_points', to='events.event', verbose_name='Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_long_points', to='register.player', verbose_name='Player')),
            ],
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
        migrations.AddConstraint(
            model_name='eventpoints',
            constraint=models.UniqueConstraint(fields=('event', 'player', 'is_net'), name='unique_points'),
        ),
    ]
