# Generated by Django 5.1.3 on 2025-11-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damcup', '0009_eventpoints_delete_scores_eventpoints_unique_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventPoints',
        ),
    ]
